version: '3'

services:

  # Data API and authentication/authorization
  api:
    image: node
    container_name: api
    build:
      context: ./
      args:
        NODE_ENV: development
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/app

  # MongoDB
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    
